version: '3.8'

services:
  server-print:
    image: geolirk.cr.cloud.ru/efgi-serv-print-257:latest
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
